# Generated by Django 5.0.4 on 2024-04-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now=True, verbose_name='date')),
                ('Time', models.DateTimeField(auto_now=True, verbose_name='time')),
                ('Frequency', models.IntegerField(verbose_name='frequency')),
                ('Device', models.CharField(max_length=6, verbose_name='device')),
                ('Location', models.CharField(max_length=5, verbose_name='location')),
                ('Grid_1', models.IntegerField(verbose_name='grid_1')),
                ('Grid_2', models.IntegerField(verbose_name='grid_2')),
                ('Lat', models.IntegerField(verbose_name='lat')),
                ('Long', models.IntegerField(verbose_name='long')),
                ('NearHit', models.BooleanField(verbose_name='nearhit')),
            ],
        ),
    ]
