# Generated by Django 5.0.4 on 2024-04-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_planning_api', '0002_item_alter_emdata_device_alter_emdata_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emdata',
            name='Device',
            field=models.CharField(max_length=6, verbose_name='device'),
        ),
        migrations.AlterField(
            model_name='emdata',
            name='Location',
            field=models.CharField(max_length=5, verbose_name='location'),
        ),
    ]
