# Generated by Django 5.0.4 on 2024-04-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('em_planning_arch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='EMData',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
